# Tutoriux Parameters
app:

  metadata:
    title: 'Tutoriux'
    description: 'Tutoriux, share your knowledge'
    keywords: 'Tutoriux, Tutorials, keywords'

  emails:
    system_email: 'no-reply@tutoriux.com'
    feedback: 'feedback@tutoriux.com'