#  Notes:
#  Cache configuration are found under framework.yaml
#  Cache services are found under services.yaml

parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'pgsql://tutoriux:tutoriux@localhost:5432/Tutoriux3'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '%env(POSTGRESQL_VERSION)%'
        charset: UTF-8
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore

        # Cache config
        metadata_cache_driver:
            type: service
            id: doctrine.metadata_cache_driver
        query_cache_driver:
            type: service
            id: doctrine.query_cache_driver
        result_cache_driver:
            type: service
            id: doctrine.result_cache_driver
        second_level_cache:
            region_cache_driver:
                type: service
                id: doctrine.second_level_cache
            enabled: true
            region_lifetime: 1800

        # Mapping config
        auto_mapping: true
        mappings:
            app:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine_mappings/_app/'
                prefix: 'App\Entity'
                alias: App
                is_bundle: false
            content:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine_mappings/content/'
                prefix: 'App\Entity\Content'
                alias: Content
                is_bundle: false
            document:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine_mappings/document/'
                prefix: 'App\Entity\Document'
                alias: Document
                is_bundle: false
            Media:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine_mappings/media/'
                prefix: 'App\Entity\Media'
                alias: Media
                is_bundle: false
            school:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine_mappings/school/'
                prefix: 'App\Entity\School'
                alias: School
                is_bundle: false