# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
#

# Snc Redis
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%env(REDIS_URL)%"
            logging: '%kernel.debug%'
        doctrine:
            type: phpredis
            alias: doctrine
            dsn: "%env(REDIS_URL)%"
            logging: '%kernel.debug%'
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
        result_cache:
            client: doctrine
            entity_manager: default
        query_cache:
            client: doctrine
            entity_manager: default