<?php

namespace App\Repository;

use Exception;
use Tutoriux\DoctrineBehaviorsBundle\Model as TutoriuxORMBehaviors;
use App\Library\BaseEntityRepository;
use Tutoriux\DoctrineBehaviorsBundle\Model\Repository\TranslatableRepositoryInterface;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends BaseEntityRepository implements TranslatableRepositoryInterface
{
    use TutoriuxORMBehaviors\Repository\TranslatableEntityRepository;

    /**
     * @param null $queryBuilder
     * @param null $sectionId
     * @param null $textId
     * @return mixed|null
     */
    public function findLastUpdate($queryBuilder = null, $sectionId = null, $textId = null)
    {
        if (!$queryBuilder) {
            $queryBuilder = $this->createQueryBuilder('t');
        }

        if ($sectionId) {
            $queryBuilder->andWhere('t.section = :sectionId')
                ->setParameter('sectionId', $sectionId);
        }

        if ($textId) {
            $queryBuilder->andWhere('t.id = :textId')
                ->setParameter('textId', $textId);
        }

        try {
            return $queryBuilder->select('t.updatedAt')
                ->addOrderBy('t.updatedAt', 'DESC')
                ->setMaxResults(1)
                ->getQuery()->getSingleScalarResult();
        } catch (Exception $e) {
            return null;
        }
    }
}