# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Library,Repository,Form,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Library\BaseController:
        arguments: ['@App\Services\ApplicationCore']
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Public

#    App\Services\DoctrineInit:
#        public: true

    # Private

    App\Services\ApplicationCore:
        autowire: true
        calls:
            - ['setDoctrineInit', ['@App\Services\DoctrineInitCallable']]

    App\Routing\MappingDirectoryLoader:
        arguments: ['@file_locator']
        tags: [routing.loader]

    App\Routing\MappingYamlFileLoader:
        arguments: ['@file_locator', '@database_connection']
        tags: [routing.loader]

    App\Listeners\DoctrineSubscriber:
        arguments: ['@App\Services\DoctrineInit']
        tags:
            - { name: doctrine.event_subscriber }



    # Defined multiple time so we can change the namespace. Might be a bug with doctrine
    # Workaround to force doctrine namespace on redis cache while using symfony TraceableAdapter (cache pool)
    doctrine.metadata_cache_driver:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments: ['@cache.pool.doctrine_system']
        calls:
            - [setNamespace, ['dmc:']]
    doctrine.query_cache_driver:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments: ['@cache.pool.doctrine_system']
        calls:
            - [setNamespace, ['dqc:']]
    doctrine.result_cache_driver:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments: ['@cache.pool.doctrine_result']
        calls:
            - [setNamespace, ['drc:']]
    doctrine.second_level_cache:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments: ['@cache.pool.doctrine_second_level']
        calls:
            - [setNamespace, ['dslc:']]