App\Entity\Content\ContentTranslation:
  type: entity
  table: content_translation
  repositoryClass: App\Repository\Content\ContentTranslationRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: true
    content:
      type: text
      nullable: true
    schemaVersion:
      type: integer
      nullable: false
  lifecycleCallbacks: {  }
  oneToMany:
    versions:
      targetEntity: App\Entity\Content\ContentVersion
      mappedBy: master
      orderBy: { 'createdAt': 'DESC' }