site_login:
  path:  /login
  controller: App\Controller\Site\Security::login

site_login_check:
  path:  /login-check
  defaults:
    _tutoriuxContext: 'site'
    _tutoriuxEnabled: true
    _tutoriuxRequest:
      sectionId: 1

site_logout:
  path:  /logout
  defaults:
    _tutoriuxContext: 'site'
    _tutoriuxEnabled: true
    _tutoriuxRequest:
      sectionId: 1