site_login:
  path:  /login
  controller: App\Controller\Site\SecurityController::login
  defaults:
    _tutoriuxContext: 'site'
    _tutoriuxEnabled: true
    _tutoriuxRequest:
      sectionId: 1

site_login_check:
  path:  /login-check
  defaults:
    _tutoriuxContext: 'site'
    _tutoriuxEnabled: true
    _tutoriuxRequest:
      sectionId: 1

site_logout:
  path:  /logout
  defaults:
    _tutoriuxContext: 'site'
    _tutoriuxEnabled: true
    _tutoriuxRequest:
      sectionId: 1

# Password lost

site_user_password_lost:
  path:  /reset-password
  controller: App\Controller\Site\SecurityController::passwordLost
  defaults:
    _tutoriuxContext: 'site'
    _tutoriuxEnabled: true
    _tutoriuxRequest:
      sectionId: 1

site_user_password_lost_change:
  path:  /change-password
  controller: App\Controller\Site\SecurityController::passwordLostChange
  defaults:
    _tutoriuxContext: 'site'
    _tutoriuxEnabled: true
    _tutoriuxRequest:
      sectionId: 1