# Users
# !!! The path must be preceded by '/u/' to be caught by the firewall

# Register

site_user_register:
  path: /register
  controller: App\Controller\Site\User\RegisterController::register
  defaults:
    _tutoriuxContext: 'site'
    _tutoriuxEnabled: true
    _tutoriuxRequest:
      sectionId: 1

site_user_register_confirm:
  path: /register-confirm
  controller: App\Controller\Site\User\RegisterController::registerConfirm
  defaults:
    _tutoriuxContext: 'site'
    _tutoriuxEnabled: true
    _tutoriuxRequest:
      sectionId: 1

# Notification

site_notification_viewed:
  path:  /u/notification/viewed
  controller: App\Controller\Site\NotificationController::viewed
  options:
    expose: true

site_notification_toastr:
  path:  /u/notification/toastr
  controller: App\Controller\Site\NotificationController::toastr
  options:
    expose: true