App\Entity\Locale:
  type: entity
  repositoryClass: App\Repository\LocaleRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: true
    code:
      type: string
      length: 255
      nullable: true
    ordering:
      type: integer
      nullable: true
    active:
      type: boolean
      nullable: true